# Generated by Django 4.2.7 on 2023-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_Category',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_discribe',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
