# Generated by Django 4.2.7 on 2023-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_blog_category_blog_blog_discribe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_category', models.CharField(max_length=50)),
                ('blog_discribe', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
