# Generated by Django 4.2.7 on 2023-11-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_info_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField()),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_likes', models.IntegerField()),
                ('blog_hates', models.IntegerField()),
                ('blog_date', models.DateField()),
                ('blog_category', models.CharField(max_length=50)),
                ('blog_discribe', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='blog_info',
        ),
    ]
